variables:
  PROJECT_NAME: process
  IMAGE_PREFIX: qxcr.xyz/lowcode

before_script:
  - go get git.internal.yunify.com/qxp/misc
  - go get ./...

stages:
  - lint
  - test
  - build
  - deploy

go_lint:
  stage: lint
  script:
    - golint -set_exit_status $(go list ./... | grep -v /vendor/)

unit_tests:
  stage: test
  script:
    - go test ./...

coverage_test:
  stage: test
  script:
    - go test -cover ./...

compile_test:
  stage: build
  only:
    - /^release\/*/
  script:
    - go mod tidy
    - go mod vendor
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - docker build -t "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG" .
    - docker push "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG"
    - docker rmi "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG"

compile_staging:
  stage: build
  only:
    - tags
    - feature/staging
  except:
    - branches
  script:
    - go mod tidy
    - go mod vendor
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - docker build -t $IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG .
    - docker push $IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG
    - docker tag $IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG $IMAGE_PREFIX/$PROJECT_NAME:latest
    - docker push $IMAGE_PREFIX/$PROJECT_NAME:latest
    - docker tag $IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG $IMAGE_PREFIX/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker push $IMAGE_PREFIX/$PROJECT_NAME:$CI_COMMIT_REF_NAME
    - docker rmi "$IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG"

alpha:
  stage: deploy
  only:
    - alpha
  script:
    - chmod +x dev_auto.sh
    - make dev

test:
  stage: deploy
  only:
    - /^release\/*/
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    - /opt/upImage.sh $IMAGE_PREFIX/$PROJECT_NAME:$IMAGE_TAG $CI_COMMIT_REF_NAME
staging:
  stage: deploy
  only:
    - tags
    - master
  except:
    - branches
  script:
    - IMAGE_TAG="v$(date "+%Y%m%d")-$(git rev-parse --short HEAD)"
    #    - helm --host=$HELM_STAGING upgrade $PROJECT_NAME /root/deployment/$PROJECT_NAME --set image.tag=$IMAGE_TAG --set namespace=lowcode
    - helm upgrade $PROJECT_NAME /root/quanxiang_charts_staging/$PROJECT_NAME --kubeconfig ~/.kube/config_staging --set image.tag=$IMAGE_TAG --set image.repo=$IMAGE_PREFIX -n lowcode